// src/components/Materials.tsx
import React, { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from './ui/card';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from './ui/dialog';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from './ui/table';
import { Badge } from './ui/badge';
import { Plus, Search, Edit, Trash2, Loader2, Package } from 'lucide-react';
import { projectId, publicAnonKey } from '../utils/supabase/info';
import { toast } from 'sonner@2.0.3';

interface MaterialsProps {
  token: string;
  user: any;
}

interface Material {
  id: string;
  codigo_barras: string;
  nome: string;
  tipo: string;
  cor: string | null;
  quantidade_atual: number;
  unidade_medida: string;
  localizacao_pavilhao: string | null;
  data_cadastro: string;
}

export function Materials({ token, user }: MaterialsProps) {
  const [materials, setMaterials] = useState<Material[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterTipo, setFilterTipo] = useState('todos');
  const [dialogOpen, setDialogOpen] = useState(false);
  const [editingMaterial, setEditingMaterial] = useState<Material | null>(null);
  const [submitting, setSubmitting] = useState(false);

  // Form state
  const [formData, setFormData] = useState({
    nome: '',
    tipo: 'Tecido',
    cor: '',
    quantidade_atual: '',
    unidade_medida: 'kg',
    localizacao_pavilhao: '',
    codigo_barras: '',
  });

  const fetchMaterials = async () => {
    try {
      const params = new URLSearchParams();
      if (filterTipo !== 'todos') params.append('tipo', filterTipo);
      if (searchTerm) params.append('search', searchTerm);

      const response = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-ed830bfb/materials?${params}`,
        {
          headers: {
            'Authorization': `Bearer ${publicAnonKey}`,
            'X-Access-Token': token,
          },
        }
      );

      if (!response.ok) {
        throw new Error('Erro ao carregar materiais');
      }

      const data = await response.json();
      setMaterials(data.materials);
    } catch (error: any) {
      console.error('Error fetching materials:', error);
      toast.error('Erro ao carregar materiais');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchMaterials();
  }, [filterTipo, searchTerm]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!formData.nome || !formData.tipo) {
      toast.error('Preencha os campos obrigatórios');
      return;
    }

    setSubmitting(true);

    try {
      const url = editingMaterial
        ? `https://${projectId}.supabase.co/functions/v1/make-server-ed830bfb/materials/${editingMaterial.id}`
        : `https://${projectId}.supabase.co/functions/v1/make-server-ed830bfb/materials`;

      const response = await fetch(url, {
        method: editingMaterial ? 'PUT' : 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${publicAnonKey}`,
          'X-Access-Token': token,
        },
        body: JSON.stringify(formData),
      });

      if (!response.ok) {
        const data = await response.json();
        throw new Error(data.error || 'Erro ao salvar material');
      }

      toast.success(editingMaterial ? 'Material atualizado!' : 'Material criado!');
      setDialogOpen(false);
      resetForm();
      fetchMaterials();
    } catch (error: any) {
      console.error('Erro ao salvar material:', error);
      toast.error(error.message);
    } finally {
      setSubmitting(false);
    }
  };

  const handleEdit = (material: Material) => {
    setEditingMaterial(material);
    setFormData({
      nome: material.nome,
      tipo: material.tipo,
      cor: material.cor || '',
      quantidade_atual: material.quantidade_atual.toString(),
      unidade_medida: material.unidade_medida,
      localizacao_pavilhao: material.localizacao_pavilhao || '',
      codigo_barras: material.codigo_barras,
    });
    setDialogOpen(true);
  };

  const handleDelete = async (material: Material) => {
    if (!confirm(`Deseja realmente excluir "${material.nome}"?`)) {
      return;
    }

    try {
      const response = await fetch(
        `https://${projectId}.supabase.co/functions/v1/make-server-ed830bfb/materials/${material.id}`,
        {
          method: 'DELETE',
          headers: {
            'Authorization': `Bearer ${publicAnonKey}`,
            'X-Access-Token': token,
          },
        }
      );

      if (!response.ok) {
        throw new Error('Erro ao excluir material');
      }

      toast.success('Material excluído!');
      fetchMaterials();
    } catch (error: any) {
      console.error('Erro ao excluir material:', error);
      toast.error(error.message);
    }
  };

  const resetForm = () => {
    setFormData({
      nome: '',
      tipo: 'Tecido',
      cor: '',
      quantidade_atual: '',
      unidade_medida: 'kg',
      localizacao_pavilhao: '',
      codigo_barras: '',
    });
    setEditingMaterial(null);
  };

  const handleDialogOpenChange = (open: boolean) => {
    setDialogOpen(open);
    if (!open) {
      resetForm();
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold text-slate-900">Materiais</h2>
          <p className="text-slate-600 mt-1">
            Gerencie o estoque de sobras do pavilhão
          </p>
        </div>

        <Dialog open={dialogOpen} onOpenChange={handleDialogOpenChange}>
          <DialogTrigger asChild>
            <Button className="bg-orange-500 hover:bg-orange-600">
              <Plus className="w-4 h-4 mr-2" />
              Novo Material
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>
                {editingMaterial ? 'Editar Material' : 'Novo Material'}
              </DialogTitle>
              <DialogDescription>
                Preencha os dados do material abaixo
              </DialogDescription>
            </DialogHeader>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="nome">Nome do Material *</Label>
                  <Input
                    id="nome"
                    value={formData.nome}
                    onChange={(e) => setFormData({ ...formData, nome: e.target.value })}
                    placeholder="Ex: Retalho Jeans Indigo"
                    disabled={submitting}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="codigo_barras">Código de Barras</Label>
                  <Input
                    id="codigo_barras"
                    value={formData.codigo_barras}
                    onChange={(e) => setFormData({ ...formData, codigo_barras: e.target.value })}
                    placeholder="Auto-gerado se vazio"
                    disabled={submitting || !!editingMaterial}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="tipo">Tipo *</Label>
                  <Select
                    value={formData.tipo}
                    onValueChange={(value) => setFormData({ ...formData, tipo: value })}
                    disabled={submitting}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="Tecido">Tecido</SelectItem>
                      <SelectItem value="Couro">Couro</SelectItem>
                      <SelectItem value="Plástico">Plástico</SelectItem>
                      <SelectItem value="Espuma">Espuma</SelectItem>
                      <SelectItem value="Papel">Papel</SelectItem>
                      <SelectItem value="Outros">Outros</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="cor">Cor</Label>
                  <Input
                    id="cor"
                    value={formData.cor}
                    onChange={(e) => setFormData({ ...formData, cor: e.target.value })}
                    placeholder="Ex: Azul Escuro"
                    disabled={submitting}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="quantidade">Quantidade Inicial</Label>
                  <Input
                    id="quantidade"
                    type="number"
                    step="0.01"
                    value={formData.quantidade_atual}
                    onChange={(e) => setFormData({ ...formData, quantidade_atual: e.target.value })}
                    placeholder="0.00"
                    disabled={submitting || !!editingMaterial}
                  />
                </div>

                <div className="space-y-2">
                  <Label htmlFor="unidade">Unidade de Medida</Label>
                  <Select
                    value={formData.unidade_medida}
                    onValueChange={(value) => setFormData({ ...formData, unidade_medida: value })}
                    disabled={submitting}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="kg">kg (Quilograma)</SelectItem>
                      <SelectItem value="m">m (Metro)</SelectItem>
                      <SelectItem value="m²">m² (Metro Quadrado)</SelectItem>
                      <SelectItem value="un">un (Unidade)</SelectItem>
                    </SelectContent>
                  </Select>
                </div>

                <div className="space-y-2 col-span-2">
                  <Label htmlFor="localizacao">Localização no Pavilhão</Label>
                  <Input
                    id="localizacao"
                    value={formData.localizacao_pavilhao}
                    onChange={(e) => setFormData({ ...formData, localizacao_pavilhao: e.target.value })}
                    placeholder="Ex: A-01, B-15, etc"
                    disabled={submitting}
                  />
                </div>
              </div>

              <div className="flex justify-end space-x-2 pt-4">
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => handleDialogOpenChange(false)}
                  disabled={submitting}
                >
                  Cancelar
                </Button>
                <Button
                  type="submit"
                  className="bg-orange-500 hover:bg-orange-600"
                  disabled={submitting}
                >
                  {submitting ? (
                    <>
                      <Loader2 className="w-4 h-4 mr-2 animate-spin" />
                      Salvando...
                    </>
                  ) : (
                    'Salvar'
                  )}
                </Button>
              </div>
            </form>
          </DialogContent>
        </Dialog>
      </div>

      {/* Filters */}
      <Card>
        <CardContent className="pt-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-slate-400 w-4 h-4" />
              <Input
                placeholder="Buscar por nome, código ou cor..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="pl-10"
              />
            </div>

            <Select value={filterTipo} onValueChange={setFilterTipo}>
              <SelectTrigger>
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="todos">Todos os Tipos</SelectItem>
                <SelectItem value="Tecido">Tecido</SelectItem>
                <SelectItem value="Couro">Couro</SelectItem>
                <SelectItem value="Plástico">Plástico</SelectItem>
                <SelectItem value="Espuma">Espuma</SelectItem>
                <SelectItem value="Papel">Papel</SelectItem>
                <SelectItem value="Outros">Outros</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* Materials Table */}
      <Card>
        <CardHeader>
          <CardTitle>
            {materials.length} {materials.length === 1 ? 'Material' : 'Materiais'}
          </CardTitle>
        </CardHeader>
        <CardContent>
          {loading ? (
            <div className="flex justify-center py-12">
              <Loader2 className="w-8 h-8 animate-spin text-orange-500" />
            </div>
          ) : materials.length === 0 ? (
            <div className="text-center py-12">
              <Package className="w-16 h-16 text-slate-300 mx-auto mb-4" />
              <p className="text-slate-600">Nenhum material encontrado</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Código</TableHead>
                    <TableHead>Nome</TableHead>
                    <TableHead>Tipo</TableHead>
                    <TableHead>Cor</TableHead>
                    <TableHead>Quantidade</TableHead>
                    <TableHead>Localização</TableHead>
                    <TableHead className="text-right">Ações</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {materials.map((material) => (
                    <TableRow key={material.id}>
                      <TableCell className="font-mono text-sm">
                        {material.codigo_barras}
                      </TableCell>
                      <TableCell className="font-medium">
                        {material.nome}
                      </TableCell>
                      <TableCell>
                        <Badge variant="secondary">{material.tipo}</Badge>
                      </TableCell>
                      <TableCell>{material.cor || '-'}</TableCell>
                      <TableCell>
                        <span className={material.quantidade_atual < 10 ? 'text-red-600 font-semibold' : ''}>
                          {material.quantidade_atual} {material.unidade_medida}
                        </span>
                      </TableCell>
                      <TableCell>{material.localizacao_pavilhao || '-'}</TableCell>
                      <TableCell className="text-right">
                        <div className="flex justify-end space-x-2">
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleEdit(material)}
                          >
                            <Edit className="w-4 h-4" />
                          </Button>
                          <Button
                            size="sm"
                            variant="outline"
                            onClick={() => handleDelete(material)}
                            className="text-red-600 hover:text-red-700"
                          >
                            <Trash2 className="w-4 h-4" />
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

// src/pages/Materials.vue
<script setup>
import { ref, computed, onMounted } from 'vue'
import Layout from '@/components/Layout.vue'
import LoadingSpinner from '@/components/LoadingSpinner.vue'
import EmptyState from '@/components/EmptyState.vue'
import { Search, Plus, Edit, Trash2, Package, AlertCircle, X } from 'lucide-vue-next'
import { useApi } from '@/composables/useApi'
import { useAuthStore } from '@/stores/auth'

const authStore = useAuthStore()
const { fetchMaterials, createMaterial, updateMaterial, deleteMaterial } = useApi()

const materials = ref([])
const isLoading = ref(true)
const searchTerm = ref('')
const filterTipo = ref('')
const showModal = ref(false)
const editingMaterial = ref(null)
const error = ref('')
const isSubmitting = ref(false)

const formData = ref({
  codigo: '',
  descricao: '',
  tipo: 'madeira',
  quantidade: 0,
  unidade: 'kg',
  localizacao: '',
  observacoes: ''
})

const tipos = [
  { value: 'madeira', label: 'Madeira' },
  { value: 'chapa_metalica', label: 'Chapa Metálica' },
  { value: 'plastico', label: 'Plástico' },
  { value: 'vidro', label: 'Vidro' },
  { value: 'outro', label: 'Outro' }
]

const unidades = [
  { value: 'kg', label: 'Quilograma (kg)' },
  { value: 'm', label: 'Metro (m)' },
  { value: 'm2', label: 'Metro Quadrado (m²)' },
  { value: 'unidade', label: 'Unidade (un)' }
]

const filteredMaterials = computed(() => {
  let filtered = [...materials.value]

  if (searchTerm.value) {
    const search = searchTerm.value.toLowerCase()
    filtered = filtered.filter(m =>
      m.descricao.toLowerCase().includes(search) ||
      m.codigo.toLowerCase().includes(search)
    )
  }

  if (filterTipo.value) {
    filtered = filtered.filter(m => m.tipo === filterTipo.value)
  }

  return filtered
})

function getStockColor(quantidade) {
  if (quantidade < 10) return 'text-red-600 bg-red-100'
  if (quantidade < 50) return 'text-yellow-600 bg-yellow-100'
  return 'text-green-600 bg-green-100'
}

function getTipoLabel(tipo) {
  const found = tipos.find(t => t.value === tipo)
  return found ? found.label : tipo
}

async function loadMaterials() {
  try {
    const data = await fetchMaterials()
    materials.value = data.materials || []
  } catch (err) {
    console.error('Error fetching materials:', err)
  } finally {
    isLoading.value = false
  }
}

function openModal(material) {
  if (material) {
    editingMaterial.value = material
    formData.value = {
      codigo: material.codigo,
      descricao: material.descricao,
      tipo: material.tipo,
      quantidade: material.quantidade,
      unidade: material.unidade,
      localizacao: material.localizacao,
      observacoes: material.observacoes || ''
    }
  } else {
    editingMaterial.value = null
    formData.value = {
      codigo: '',
      descricao: '',
      tipo: 'madeira',
      quantidade: 0,
      unidade: 'kg',
      localizacao: '',
      observacoes: ''
    }
  }
  error.value = ''
  showModal.value = true
}

function closeModal() {
  showModal.value = false
  editingMaterial.value = null
  error.value = ''
}

async function handleSubmit() {
  if (!authStore.token) {
    error.value = 'Você precisa estar autenticado. Faça login novamente.'
    return
  }

  error.value = ''
  isSubmitting.value = true

  try {
    if (editingMaterial.value) {
      await updateMaterial(editingMaterial.value.id, formData.value)
    } else {
      await createMaterial(formData.value)
    }

    await loadMaterials()
    closeModal()
  } catch (err) {
    error.value = err.message || 'Erro ao salvar material'
  } finally {
    isSubmitting.value = false
  }
}

async function handleDelete(id) {
  if (!confirm('Tem certeza que deseja deletar este material?')) {
    return
  }

  try {
    await deleteMaterial(id)
    await loadMaterials()
  } catch (err) {
    alert('Erro ao deletar material')
  }
}

onMounted(() => {
  loadMaterials()
})
</script>

<template>
  <Layout>
    <div class="max-w-7xl mx-auto">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
        <div>
          <h2 class="text-3xl font-bold text-gray-900 mb-2">Materiais</h2>
          <p class="text-gray-600">Gerencie o estoque de sobras</p>
        </div>
        <button
          @click="openModal()"
          class="mt-4 md:mt-0 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold flex items-center shadow-md transition-colors"
        >
          <Plus class="w-5 h-5 mr-2" />
          Novo Material
        </button>
      </div>

      <!-- Filters -->
      <div class="bg-white rounded-xl shadow-md p-6 mb-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="relative">
            <Search class="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              v-model="searchTerm"
              type="text"
              placeholder="Buscar por descrição ou código..."
              class="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
            />
          </div>

          <select
            v-model="filterTipo"
            class="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
          >
            <option value="">Todos os tipos</option>
            <option v-for="tipo in tipos" :key="tipo.value" :value="tipo.value">
              {{ tipo.label }}
            </option>
          </select>
        </div>
      </div>

      <!-- Materials Table -->
      <div class="bg-white rounded-xl shadow-md overflow-hidden">
        <LoadingSpinner v-if="isLoading" />

        <EmptyState
          v-else-if="filteredMaterials.length === 0"
          :icon="Package"
          title="Nenhum material encontrado"
          description="Adicione materiais ao estoque para começar"
          :action="{ label: 'Adicionar Material' }"
          @action="openModal()"
        />

        <div v-else class="overflow-x-auto">
          <table class="w-full">
            <thead class="bg-gray-50 border-b border-gray-200">
              <tr>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Código</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Descrição</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Tipo</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Quantidade</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Localização</th>
                <th class="px-6 py-4 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">Ações</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
              <tr v-for="material in filteredMaterials" :key="material.id" class="hover:bg-gray-50 transition-colors">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-900">
                  {{ material.codigo }}
                </td>
                <td class="px-6 py-4 text-sm font-medium text-gray-900">
                  {{ material.descricao }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                  <span class="px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-medium">
                    {{ getTipoLabel(material.tipo) }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm">
                  <span :class="['px-3 py-1 rounded-full font-semibold', getStockColor(material.quantidade)]">
                    {{ material.quantidade }} {{ material.unidade }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                  {{ material.localizacao }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <button
                    @click="openModal(material)"
                    class="text-blue-600 hover:text-blue-900 mr-3"
                    title="Editar"
                  >
                    <Edit class="w-4 h-4" />
                  </button>
                  <button
                    @click="handleDelete(material.id)"
                    class="text-red-600 hover:text-red-900"
                    title="Deletar"
                  >
                    <Trash2 class="w-4 h-4" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div v-if="showModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div class="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div class="flex items-center justify-between p-6 border-b border-gray-200">
          <h3 class="text-xl font-bold text-gray-900">
            {{ editingMaterial ? 'Editar Material' : 'Novo Material' }}
          </h3>
          <button @click="closeModal" class="text-gray-400 hover:text-gray-600">
            <X class="w-6 h-6" />
          </button>
        </div>

        <form @submit.prevent="handleSubmit" class="p-6 space-y-4">
          <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg flex items-start">
            <AlertCircle class="w-5 h-5 mr-2 flex-shrink-0 mt-0.5" />
            <span class="text-sm">{{ error }}</span>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Código *</label>
              <input
                v-model="formData.codigo"
                type="text"
                required
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                placeholder="Ex: MAT-001"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Tipo *</label>
              <select
                v-model="formData.tipo"
                required
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              >
                <option v-for="tipo in tipos" :key="tipo.value" :value="tipo.value">
                  {{ tipo.label }}
                </option>
              </select>
            </div>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Descrição *</label>
            <input
              v-model="formData.descricao"
              type="text"
              required
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="Ex: Madeira compensada 10mm"
            />
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Quantidade *</label>
              <input
                v-model.number="formData.quantidade"
                type="number"
                required
                min="0"
                step="0.01"
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Unidade *</label>
              <select
                v-model="formData.unidade"
                required
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              >
                <option v-for="unidade in unidades" :key="unidade.value" :value="unidade.value">
                  {{ unidade.label }}
                </option>
              </select>
            </div>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Localização *</label>
            <input
              v-model="formData.localizacao"
              type="text"
              required
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="Ex: Galpão A - Prateleira 3"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Observações</label>
            <textarea
              v-model="formData.observacoes"
              rows="3"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="Informações adicionais..."
            />
          </div>

          <div class="flex justify-end space-x-3 pt-4">
            <button
              type="button"
              @click="closeModal"
              class="px-6 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancelar
            </button>
            <button
              type="submit"
              :disabled="isSubmitting"
              class="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{ isSubmitting ? 'Salvando...' : 'Salvar' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </Layout>
</template>
