// src/vue-src/pages/Materials.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import Layout from '@/components/Layout.vue'
import LoadingSpinner from '@/components/LoadingSpinner.vue'
import EmptyState from '@/components/EmptyState.vue'
import { Search, Plus, Edit, Trash2, Package, AlertCircle, X } from 'lucide-vue-next'
import { useApi } from '@/composables/useApi'
import { useAuthStore } from '@/stores/auth'
import type { Material } from '@/types'

const authStore = useAuthStore()
const { fetchMaterials, createMaterial, updateMaterial, deleteMaterial } = useApi()

const materials = ref<Material[]>([])
const isLoading = ref(true)
const searchTerm = ref('')
const filterTipo = ref('')
const showModal = ref(false)
const editingMaterial = ref<Material | null>(null)
const error = ref('')
const isSubmitting = ref(false)

const formData = ref({
  codigo: '',
  descricao: '',
  tipo: 'madeira' as Material['tipo'],
  quantidade: 0,
  unidade: 'kg' as Material['unidade'],
  localizacao: '',
  observacoes: ''
})

const tipos = [
  { value: 'madeira', label: 'Madeira' },
  { value: 'chapa_metalica', label: 'Chapa Metálica' },
  { value: 'plastico', label: 'Plástico' },
  { value: 'vidro', label: 'Vidro' },
  { value: 'outro', label: 'Outro' }
]

const unidades = [
  { value: 'kg', label: 'Quilograma (kg)' },
  { value: 'm', label: 'Metro (m)' },
  { value: 'm2', label: 'Metro Quadrado (m²)' },
  { value: 'unidade', label: 'Unidade (un)' }
]

const filteredMaterials = computed(() => {
  let filtered = [...materials.value]

  if (searchTerm.value) {
    const search = searchTerm.value.toLowerCase()
    filtered = filtered.filter(m =>
      m.descricao.toLowerCase().includes(search) ||
      m.codigo.toLowerCase().includes(search)
    )
  }

  if (filterTipo.value) {
    filtered = filtered.filter(m => m.tipo === filterTipo.value)
  }

  return filtered
})

function getStockColor(quantidade: number) {
  if (quantidade < 10) return 'text-red-600 bg-red-100'
  if (quantidade < 50) return 'text-yellow-600 bg-yellow-100'
  return 'text-green-600 bg-green-100'
}

function getTipoLabel(tipo: string) {
  return tipos.find(t => t.value === tipo)?.label || tipo
}

async function loadMaterials() {
  try {
    const data = await fetchMaterials()
    materials.value = data.materials || []
  } catch (err) {
    console.error('Error fetching materials:', err)
  } finally {
    isLoading.value = false
  }
}

function openModal(material?: Material) {
  if (material) {
    editingMaterial.value = material
    formData.value = {
      codigo: material.codigo,
      descricao: material.descricao,
      tipo: material.tipo,
      quantidade: material.quantidade,
      unidade: material.unidade,
      localizacao: material.localizacao,
      observacoes: material.observacoes || ''
    }
  } else {
    editingMaterial.value = null
    formData.value = {
      codigo: '',
      descricao: '',
      tipo: 'madeira',
      quantidade: 0,
      unidade: 'kg',
      localizacao: '',
      observacoes: ''
    }
  }
  error.value = ''
  showModal.value = true
}

function closeModal() {
  showModal.value = false
  editingMaterial.value = null
  error.value = ''
}

async function handleSubmit() {
  if (!authStore.token) {
    error.value = 'Você precisa estar autenticado. Faça login novamente.'
    return
  }

  error.value = ''
  isSubmitting.value = true

  try {
    if (editingMaterial.value) {
      await updateMaterial(editingMaterial.value.id, formData.value)
    } else {
      await createMaterial(formData.value)
    }

    await loadMaterials()
    closeModal()
  } catch (err: any) {
    error.value = err.message || 'Erro ao salvar material'
  } finally {
    isSubmitting.value = false
  }
}

async function handleDelete(id: string) {
  if (!confirm('Tem certeza que deseja deletar este material?')) {
    return
  }

  try {
    await deleteMaterial(id)
    await loadMaterials()
  } catch (err) {
    alert('Erro ao deletar material')
  }
}

onMounted(() => {
  loadMaterials()
})
</script>

<template>
  <Layout>
    <div class="max-w-7xl mx-auto">
      <!-- Header -->
      <div class="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
        <div>
          <h2 class="text-3xl font-bold text-gray-900 mb-2">Materiais</h2>
          <p class="text-gray-600">Gerencie o estoque de sobras</p>
        </div>
        <button
          @click="openModal()"
          class="mt-4 md:mt-0 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold flex items-center shadow-md transition-colors"
        >
          <Plus class="w-5 h-5 mr-2" />
          Novo Material
        </button>
      </div>

      <!-- Filters -->
      <div class="bg-white rounded-xl shadow-md p-6 mb-6">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div class="relative">
            <Search class="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
            <input
              v-model="searchTerm"
              type="text"
              placeholder="Buscar por descrição ou código..."
              class="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
            />
          </div>

          <select
            v-model="filterTipo"
            class="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
          >
            <option value="">Todos os tipos</option>
            <option v-for="tipo in tipos" :key="tipo.value" :value="tipo.value">
              {{ tipo.label }}
            </option>
          </select>
        </div>
      </div>

      <!-- Materials Table -->
      <div class="bg-white rounded-xl shadow-md overflow-hidden">
        <LoadingSpinner v-if="isLoading" />

        <EmptyState
          v-else-if="filteredMaterials.length === 0"
          :icon="Package"
          title="Nenhum material encontrado"
          description="Adicione materiais ao estoque para começar"
          :action="{ label: 'Adicionar Material' }"
          @action="openModal()"
        />

        <div v-else class="overflow-x-auto">
          <table class="w-full">
            <thead class="bg-gray-50 border-b border-gray-200">
              <tr>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Código</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Descrição</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Tipo</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Quantidade</th>
                <th class="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Localização</th>
                <th class="px-6 py-4 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">Ações</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-gray-200">
              <tr v-for="material in filteredMaterials" :key="material.id" class="hover:bg-gray-50 transition-colors">
                <td class="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-900">
                  {{ material.codigo }}
                </td>
                <td class="px-6 py-4 text-sm font-medium text-gray-900">
                  {{ material.descricao }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                  <span class="px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-medium">
                    {{ getTipoLabel(material.tipo) }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm">
                  <span :class="['px-3 py-1 rounded-full font-semibold', getStockColor(material.quantidade)]">
                    {{ material.quantidade }} {{ material.unidade }}
                  </span>
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                  {{ material.localizacao }}
                </td>
                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <button
                    @click="openModal(material)"
                    class="text-blue-600 hover:text-blue-900 mr-3"
                    title="Editar"
                  >
                    <Edit class="w-4 h-4" />
                  </button>
                  <button
                    @click="handleDelete(material.id)"
                    class="text-red-600 hover:text-red-900"
                    title="Deletar"
                  >
                    <Trash2 class="w-4 h-4" />
                  </button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>

    <!-- Modal -->
    <div v-if="showModal" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50 p-4">
      <div class="bg-white rounded-xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
        <div class="flex items-center justify-between p-6 border-b border-gray-200">
          <h3 class="text-xl font-bold text-gray-900">
            {{ editingMaterial ? 'Editar Material' : 'Novo Material' }}
          </h3>
          <button @click="closeModal" class="text-gray-400 hover:text-gray-600">
            <X class="w-6 h-6" />
          </button>
        </div>

        <form @submit.prevent="handleSubmit" class="p-6 space-y-4">
          <div v-if="error" class="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg flex items-start">
            <AlertCircle class="w-5 h-5 mr-2 flex-shrink-0 mt-0.5" />
            <span class="text-sm">{{ error }}</span>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Código *</label>
              <input
                v-model="formData.codigo"
                type="text"
                required
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                placeholder="Ex: MAT-001"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Tipo *</label>
              <select
                v-model="formData.tipo"
                required
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              >
                <option v-for="tipo in tipos" :key="tipo.value" :value="tipo.value">
                  {{ tipo.label }}
                </option>
              </select>
            </div>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Descrição *</label>
            <input
              v-model="formData.descricao"
              type="text"
              required
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="Ex: Madeira compensada 10mm"
            />
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Quantidade *</label>
              <input
                v-model.number="formData.quantidade"
                type="number"
                required
                min="0"
                step="0.01"
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              />
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 mb-2">Unidade *</label>
              <select
                v-model="formData.unidade"
                required
                class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              >
                <option v-for="unidade in unidades" :key="unidade.value" :value="unidade.value">
                  {{ unidade.label }}
                </option>
              </select>
            </div>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Localização *</label>
            <input
              v-model="formData.localizacao"
              type="text"
              required
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="Ex: Galpão A - Prateleira 3"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 mb-2">Observações</label>
            <textarea
              v-model="formData.observacoes"
              rows="3"
              class="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              placeholder="Informações adicionais..."
            />
          </div>

          <div class="flex justify-end space-x-3 pt-4">
            <button
              type="button"
              @click="closeModal"
              class="px-6 py-2 border border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 transition-colors"
            >
              Cancelar
            </button>
            <button
              type="submit"
              :disabled="isSubmitting"
              class="px-6 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {{ isSubmitting ? 'Salvando...' : 'Salvar' }}
            </button>
          </div>
        </form>
      </div>
    </div>
  </Layout>
</template>

// src/pages/Materials.tsx
import { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { projectId, publicAnonKey } from '../utils/supabase/info';
import { Layout } from '../components/Layout';
import { Search, Plus, Edit, Trash2, Package, AlertCircle, X } from 'lucide-react';

interface Material {
  id: string;
  codigo_barras: string;
  nome: string;
  tipo: string;
  cor: string;
  quantidade_atual: number;
  unidade_medida: string;
  localizacao_pavilhao: string;
  data_cadastro: string;
}

export function Materials() {
  const { token } = useAuth();
  const [materials, setMaterials] = useState<Material[]>([]);
  const [filteredMaterials, setFilteredMaterials] = useState<Material[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterTipo, setFilterTipo] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingMaterial, setEditingMaterial] = useState<Material | null>(null);
  const [error, setError] = useState('');

  // Form fields
  const [formData, setFormData] = useState({
    codigo_barras: '',
    nome: '',
    tipo: '',
    cor: '',
    quantidade_atual: '',
    unidade_medida: '',
    localizacao_pavilhao: ''
  });

  const API_URL = `https://${projectId}.supabase.co/functions/v1/make-server-ed830bfb`;

  const tipos = ['Tecido', 'Papel', 'Plástico', 'Couro', 'Espuma', 'Isolante', 'Metal', 'Borracha', 'Compósito', 'Acessório'];
  const unidades = ['kg', 'm', 'm²', 'm³', 'un'];

  useEffect(() => {
    fetchMaterials();
  }, []);

  useEffect(() => {
    filterMaterials();
  }, [materials, searchTerm, filterTipo]);

  const fetchMaterials = async () => {
    try {
      const response = await fetch(`${API_URL}/materials`, {
        headers: {
          'Authorization': `Bearer ${publicAnonKey}`
        }
      });

      if (response.ok) {
        const data = await response.json();
        setMaterials(data.materials);
      }
    } catch (error) {
      console.error('Error fetching materials:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const filterMaterials = () => {
    let filtered = [...materials];

    if (searchTerm) {
      filtered = filtered.filter(m =>
        m.nome.toLowerCase().includes(searchTerm.toLowerCase()) ||
        m.codigo_barras.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    if (filterTipo) {
      filtered = filtered.filter(m => m.tipo === filterTipo);
    }

    setFilteredMaterials(filtered);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!token) {
      setError('Você precisa estar autenticado. Faça login novamente.');
      return;
    }

    console.log('Submitting material:', editingMaterial ? 'UPDATE' : 'CREATE');
    console.log('Token exists:', !!token);
    console.log('Form data:', formData);

    try {
      const url = editingMaterial
        ? `${API_URL}/materials/${editingMaterial.id}`
        : `${API_URL}/materials`;

      const method = editingMaterial ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${publicAnonKey}`,
          'X-Access-Token': token
        },
        body: JSON.stringify({
          ...formData,
          quantidade_atual: parseFloat(formData.quantidade_atual)
        })
      });

      const data = await response.json();

      console.log('Response status:', response.status);
      console.log('Response data:', data);

      if (!response.ok) {
        throw new Error(data.error || 'Erro ao salvar material');
      }

      await fetchMaterials();
      closeModal();
    } catch (err: any) {
      console.error('Material submit error:', err);
      setError(err.message);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Tem certeza que deseja deletar este material?')) {
      return;
    }

    try {
      const response = await fetch(`${API_URL}/materials/${id}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        await fetchMaterials();
      } else {
        const data = await response.json();
        alert(data.error || 'Erro ao deletar material');
      }
    } catch (error) {
      console.error('Error deleting material:', error);
      alert('Erro ao deletar material');
    }
  };

  const openModal = (material?: Material) => {
    if (material) {
      setEditingMaterial(material);
      setFormData({
        codigo_barras: material.codigo_barras,
        nome: material.nome,
        tipo: material.tipo,
        cor: material.cor,
        quantidade_atual: material.quantidade_atual.toString(),
        unidade_medida: material.unidade_medida,
        localizacao_pavilhao: material.localizacao_pavilhao
      });
    } else {
      setEditingMaterial(null);
      setFormData({
        codigo_barras: '',
        nome: '',
        tipo: '',
        cor: '',
        quantidade_atual: '',
        unidade_medida: '',
        localizacao_pavilhao: ''
      });
    }
    setError('');
    setShowModal(true);
  };

  const closeModal = () => {
    setShowModal(false);
    setEditingMaterial(null);
    setError('');
  };

  const getStockColor = (quantidade: number) => {
    if (quantidade < 10) return 'text-red-600 bg-red-100';
    if (quantidade < 50) return 'text-yellow-600 bg-yellow-100';
    return 'text-green-600 bg-green-100';
  };

  return (
    <Layout>
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
          <div>
            <h2 className="text-3xl font-bold text-gray-900 mb-2">Materiais</h2>
            <p className="text-gray-600">Gerencie o estoque de sobras</p>
          </div>
          <button
            onClick={() => openModal()}
            className="mt-4 md:mt-0 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold flex items-center shadow-md transition-colors"
          >
            <Plus className="w-5 h-5 mr-2" />
            Novo Material
          </button>
        </div>

        {/* Filters */}
        <div className="bg-white rounded-xl shadow-md p-6 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="text"
                placeholder="Buscar por nome ou código de barras..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              />
            </div>

            <select
              value={filterTipo}
              onChange={(e) => setFilterTipo(e.target.value)}
              className="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
            >
              <option value="">Todos os tipos</option>
              {tipos.map(tipo => (
                <option key={tipo} value={tipo}>{tipo}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Materials Table */}
        <div className="bg-white rounded-xl shadow-md overflow-hidden">
          {isLoading ? (
            <div className="flex items-center justify-center py-20">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
            </div>
          ) : filteredMaterials.length === 0 ? (
            <div className="text-center py-20">
              <Package className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <p className="text-gray-500 text-lg">Nenhum material encontrado</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Código</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Nome</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Tipo</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Cor</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Quantidade</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Localização</th>
                    <th className="px-6 py-4 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">Ações</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {filteredMaterials.map((material) => (
                    <tr key={material.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-900">
                        {material.codigo_barras}
                      </td>
                      <td className="px-6 py-4 text-sm font-medium text-gray-900">
                        {material.nome}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        <span className="px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-medium">
                          {material.tipo}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {material.cor}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <span className={`px-3 py-1 rounded-full font-semibold ${getStockColor(material.quantidade_atual)}`}>
                          {material.quantidade_atual} {material.unidade_medida}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {material.localizacao_pavilhao}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <button
                          onClick={() => openModal(material)}
                          className="text-blue-600 hover:text-blue-900 mr-4"
                        >
                          <Edit className="w-5 h-5 inline" />
                        </button>
                        <button
                          onClick={() => handleDelete(material.id)}
                          className="text-red-600 hover:text-red-900"
                        >
                          <Trash2 className="w-5 h-5 inline" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Modal */}
        {showModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
            <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
              <div className="p-6 border-b border-gray-200 flex items-center justify-between">
                <h3 className="text-2xl font-bold text-gray-900">
                  {editingMaterial ? 'Editar Material' : 'Novo Material'}
                </h3>
                <button
                  onClick={closeModal}
                  className="text-gray-400 hover:text-gray-600 transition-colors"
                >
                  <X className="w-6 h-6" />
                </button>
              </div>

              <form onSubmit={handleSubmit} className="p-6">
                {error && (
                  <div className="mb-4 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg flex items-start">
                    <AlertCircle className="w-5 h-5 mr-2 flex-shrink-0 mt-0.5" />
                    <span className="text-sm">{error}</span>
                  </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Código de Barras *
                    </label>
                    <input
                      type="text"
                      value={formData.codigo_barras}
                      onChange={(e) => setFormData({ ...formData, codigo_barras: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Nome *
                    </label>
                    <input
                      type="text"
                      value={formData.nome}
                      onChange={(e) => setFormData({ ...formData, nome: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Tipo *
                    </label>
                    <select
                      value={formData.tipo}
                      onChange={(e) => setFormData({ ...formData, tipo: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    >
                      <option value="">Selecione...</option>
                      {tipos.map(tipo => (
                        <option key={tipo} value={tipo}>{tipo}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Cor
                    </label>
                    <input
                      type="text"
                      value={formData.cor}
                      onChange={(e) => setFormData({ ...formData, cor: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Quantidade *
                    </label>
                    <input
                      type="number"
                      step="0.01"
                      value={formData.quantidade_atual}
                      onChange={(e) => setFormData({ ...formData, quantidade_atual: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Unidade de Medida *
                    </label>
                    <select
                      value={formData.unidade_medida}
                      onChange={(e) => setFormData({ ...formData, unidade_medida: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    >
                      <option value="">Selecione...</option>
                      {unidades.map(unidade => (
                        <option key={unidade} value={unidade}>{unidade}</option>
                      ))}
                    </select>
                  </div>

                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Localização no Pavilhão
                    </label>
                    <input
                      type="text"
                      value={formData.localizacao_pavilhao}
                      onChange={(e) => setFormData({ ...formData, localizacao_pavilhao: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      placeholder="Ex: A1, B2, etc."
                    />
                  </div>
                </div>

                <div className="mt-6 flex justify-end space-x-3">
                  <button
                    type="button"
                    onClick={closeModal}
                    className="px-6 py-3 border border-gray-300 rounded-lg font-semibold text-gray-700 hover:bg-gray-50 transition-colors"
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold transition-colors"
                  >
                    {editingMaterial ? 'Atualizar' : 'Criar'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}
