// src/components/EmptyState.tsx
import { LucideIcon } from 'lucide-react';

interface EmptyStateProps {
  icon: LucideIcon;
  title: string;
  description?: string;
  action?: {
    label: string;
    onClick: () => void;
  };
}

export function EmptyState({ icon: Icon, title, description, action }: EmptyStateProps) {
  return (
    <div className="text-center py-16">
      <div className="flex justify-center mb-4">
        <div className="bg-gray-100 p-6 rounded-full">
          <Icon className="w-12 h-12 text-gray-400" />
        </div>
      </div>
      <h3 className="text-lg font-semibold text-gray-900 mb-2">{title}</h3>
      {description && (
        <p className="text-gray-600 text-sm mb-6 max-w-sm mx-auto">{description}</p>
      )}
      {action && (
        <button
          onClick={action.onClick}
          className="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg font-medium transition-colors"
        >
          {action.label}
        </button>
      )}
    </div>
  );
}

// src/components/EmptyState.vue
<script setup>
const props = defineProps({
  icon: Object,
  title: String,
  description: String,
  action: Object
})

const emit = defineEmits(['action'])
</script>

<template>
  <div class="text-center py-16">
    <div class="flex justify-center mb-4">
      <div class="bg-gray-100 p-6 rounded-full">
        <component :is="icon" class="w-12 h-12 text-gray-400" />
      </div>
    </div>
    <h3 class="text-lg font-semibold text-gray-900 mb-2">{{ title }}</h3>
    <p v-if="description" class="text-gray-600 text-sm mb-6 max-w-sm mx-auto">
      {{ description }}
    </p>
    <button
      v-if="action"
      @click="$emit('action')"
      class="bg-blue-600 hover:bg-blue-700 text-white px-6 py-2 rounded-lg font-medium transition-colors"
    >
      {{ action.label }}
    </button>
  </div>
</template>
