// src/pages/Materials.tsx
import { useEffect, useState } from 'react';
import { useAuth } from '../contexts/AuthContext';
import { projectId, publicAnonKey } from '../utils/supabase/info';
import { Layout } from '../components/Layout';
import { Search, Plus, Edit, Trash2, Package, AlertCircle, X } from 'lucide-react';

interface Material {
  id: string;
  codigo_barras: string;
  nome: string;
  tipo: string;
  cor: string;
  quantidade_atual: number;
  unidade_medida: string;
  localizacao_pavilhao: string;
  data_cadastro: string;
}

export function Materials() {
  const { token } = useAuth();
  const [materials, setMaterials] = useState<Material[]>([]);
  const [filteredMaterials, setFilteredMaterials] = useState<Material[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchTerm, setSearchTerm] = useState('');
  const [filterTipo, setFilterTipo] = useState('');
  const [showModal, setShowModal] = useState(false);
  const [editingMaterial, setEditingMaterial] = useState<Material | null>(null);
  const [error, setError] = useState('');

  // Form fields
  const [formData, setFormData] = useState({
    codigo_barras: '',
    nome: '',
    tipo: '',
    cor: '',
    quantidade_atual: '',
    unidade_medida: '',
    localizacao_pavilhao: ''
  });

  const API_URL = `https://${projectId}.supabase.co/functions/v1/make-server-ed830bfb`;

  const tipos = ['Tecido', 'Papel', 'Plástico', 'Couro', 'Espuma', 'Isolante', 'Metal', 'Borracha', 'Compósito', 'Acessório'];
  const unidades = ['kg', 'm', 'm²', 'm³', 'un'];

  useEffect(() => {
    fetchMaterials();
  }, []);

  useEffect(() => {
    filterMaterials();
  }, [materials, searchTerm, filterTipo]);

  const fetchMaterials = async () => {
    try {
      const response = await fetch(`${API_URL}/materials`, {
        headers: {
          'Authorization': `Bearer ${publicAnonKey}`
        }
      });

      if (response.ok) {
        const data = await response.json();
        setMaterials(data.materials);
      }
    } catch (error) {
      console.error('Error fetching materials:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const filterMaterials = () => {
    let filtered = [...materials];

    if (searchTerm) {
      filtered = filtered.filter(m =>
        m.nome.toLowerCase().includes(searchTerm.toLowerCase()) ||
        m.codigo_barras.toLowerCase().includes(searchTerm.toLowerCase())
      );
    }

    if (filterTipo) {
      filtered = filtered.filter(m => m.tipo === filterTipo);
    }

    setFilteredMaterials(filtered);
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!token) {
      setError('Você precisa estar autenticado. Faça login novamente.');
      return;
    }

    console.log('Submitting material:', editingMaterial ? 'UPDATE' : 'CREATE');
    console.log('Token exists:', !!token);
    console.log('Form data:', formData);

    try {
      const url = editingMaterial
        ? `${API_URL}/materials/${editingMaterial.id}`
        : `${API_URL}/materials`;

      const method = editingMaterial ? 'PUT' : 'POST';

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${publicAnonKey}`,
          'X-Access-Token': token
        },
        body: JSON.stringify({
          ...formData,
          quantidade_atual: parseFloat(formData.quantidade_atual)
        })
      });

      const data = await response.json();

      console.log('Response status:', response.status);
      console.log('Response data:', data);

      if (!response.ok) {
        throw new Error(data.error || 'Erro ao salvar material');
      }

      await fetchMaterials();
      closeModal();
    } catch (err: any) {
      console.error('Material submit error:', err);
      setError(err.message);
    }
  };

  const handleDelete = async (id: string) => {
    if (!confirm('Tem certeza que deseja deletar este material?')) {
      return;
    }

    try {
      const response = await fetch(`${API_URL}/materials/${id}`, {
        method: 'DELETE',
        headers: {
          'Authorization': `Bearer ${token}`
        }
      });

      if (response.ok) {
        await fetchMaterials();
      } else {
        const data = await response.json();
        alert(data.error || 'Erro ao deletar material');
      }
    } catch (error) {
      console.error('Error deleting material:', error);
      alert('Erro ao deletar material');
    }
  };

  const openModal = (material?: Material) => {
    if (material) {
      setEditingMaterial(material);
      setFormData({
        codigo_barras: material.codigo_barras,
        nome: material.nome,
        tipo: material.tipo,
        cor: material.cor,
        quantidade_atual: material.quantidade_atual.toString(),
        unidade_medida: material.unidade_medida,
        localizacao_pavilhao: material.localizacao_pavilhao
      });
    } else {
      setEditingMaterial(null);
      setFormData({
        codigo_barras: '',
        nome: '',
        tipo: '',
        cor: '',
        quantidade_atual: '',
        unidade_medida: '',
        localizacao_pavilhao: ''
      });
    }
    setError('');
    setShowModal(true);
  };

  const closeModal = () => {
    setShowModal(false);
    setEditingMaterial(null);
    setError('');
  };

  const getStockColor = (quantidade: number) => {
    if (quantidade < 10) return 'text-red-600 bg-red-100';
    if (quantidade < 50) return 'text-yellow-600 bg-yellow-100';
    return 'text-green-600 bg-green-100';
  };

  return (
    <Layout>
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center md:justify-between mb-6">
          <div>
            <h2 className="text-3xl font-bold text-gray-900 mb-2">Materiais</h2>
            <p className="text-gray-600">Gerencie o estoque de sobras</p>
          </div>
          <button
            onClick={() => openModal()}
            className="mt-4 md:mt-0 bg-blue-600 hover:bg-blue-700 text-white px-6 py-3 rounded-lg font-semibold flex items-center shadow-md transition-colors"
          >
            <Plus className="w-5 h-5 mr-2" />
            Novo Material
          </button>
        </div>

        {/* Filters */}
        <div className="bg-white rounded-xl shadow-md p-6 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
              <input
                type="text"
                placeholder="Buscar por nome ou código de barras..."
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
              />
            </div>

            <select
              value={filterTipo}
              onChange={(e) => setFilterTipo(e.target.value)}
              className="px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
            >
              <option value="">Todos os tipos</option>
              {tipos.map(tipo => (
                <option key={tipo} value={tipo}>{tipo}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Materials Table */}
        <div className="bg-white rounded-xl shadow-md overflow-hidden">
          {isLoading ? (
            <div className="flex items-center justify-center py-20">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
            </div>
          ) : filteredMaterials.length === 0 ? (
            <div className="text-center py-20">
              <Package className="w-16 h-16 text-gray-300 mx-auto mb-4" />
              <p className="text-gray-500 text-lg">Nenhum material encontrado</p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Código</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Nome</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Tipo</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Cor</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Quantidade</th>
                    <th className="px-6 py-4 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">Localização</th>
                    <th className="px-6 py-4 text-right text-xs font-semibold text-gray-600 uppercase tracking-wider">Ações</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {filteredMaterials.map((material) => (
                    <tr key={material.id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-mono text-gray-900">
                        {material.codigo_barras}
                      </td>
                      <td className="px-6 py-4 text-sm font-medium text-gray-900">
                        {material.nome}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        <span className="px-2 py-1 bg-blue-100 text-blue-800 rounded-full text-xs font-medium">
                          {material.tipo}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {material.cor}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm">
                        <span className={`px-3 py-1 rounded-full font-semibold ${getStockColor(material.quantidade_atual)}`}>
                          {material.quantidade_atual} {material.unidade_medida}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
                        {material.localizacao_pavilhao}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <button
                          onClick={() => openModal(material)}
                          className="text-blue-600 hover:text-blue-900 mr-4"
                        >
                          <Edit className="w-5 h-5 inline" />
                        </button>
                        <button
                          onClick={() => handleDelete(material.id)}
                          className="text-red-600 hover:text-red-900"
                        >
                          <Trash2 className="w-5 h-5 inline" />
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        {/* Modal */}
        {showModal && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50">
            <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto">
              <div className="p-6 border-b border-gray-200 flex items-center justify-between">
                <h3 className="text-2xl font-bold text-gray-900">
                  {editingMaterial ? 'Editar Material' : 'Novo Material'}
                </h3>
                <button
                  onClick={closeModal}
                  className="text-gray-400 hover:text-gray-600 transition-colors"
                >
                  <X className="w-6 h-6" />
                </button>
              </div>

              <form onSubmit={handleSubmit} className="p-6">
                {error && (
                  <div className="mb-4 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg flex items-start">
                    <AlertCircle className="w-5 h-5 mr-2 flex-shrink-0 mt-0.5" />
                    <span className="text-sm">{error}</span>
                  </div>
                )}

                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Código de Barras *
                    </label>
                    <input
                      type="text"
                      value={formData.codigo_barras}
                      onChange={(e) => setFormData({ ...formData, codigo_barras: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Nome *
                    </label>
                    <input
                      type="text"
                      value={formData.nome}
                      onChange={(e) => setFormData({ ...formData, nome: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Tipo *
                    </label>
                    <select
                      value={formData.tipo}
                      onChange={(e) => setFormData({ ...formData, tipo: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    >
                      <option value="">Selecione...</option>
                      {tipos.map(tipo => (
                        <option key={tipo} value={tipo}>{tipo}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Cor
                    </label>
                    <input
                      type="text"
                      value={formData.cor}
                      onChange={(e) => setFormData({ ...formData, cor: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Quantidade *
                    </label>
                    <input
                      type="number"
                      step="0.01"
                      value={formData.quantidade_atual}
                      onChange={(e) => setFormData({ ...formData, quantidade_atual: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    />
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Unidade de Medida *
                    </label>
                    <select
                      value={formData.unidade_medida}
                      onChange={(e) => setFormData({ ...formData, unidade_medida: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      required
                    >
                      <option value="">Selecione...</option>
                      {unidades.map(unidade => (
                        <option key={unidade} value={unidade}>{unidade}</option>
                      ))}
                    </select>
                  </div>

                  <div className="md:col-span-2">
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Localização no Pavilhão
                    </label>
                    <input
                      type="text"
                      value={formData.localizacao_pavilhao}
                      onChange={(e) => setFormData({ ...formData, localizacao_pavilhao: e.target.value })}
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
                      placeholder="Ex: A1, B2, etc."
                    />
                  </div>
                </div>

                <div className="mt-6 flex justify-end space-x-3">
                  <button
                    type="button"
                    onClick={closeModal}
                    className="px-6 py-3 border border-gray-300 rounded-lg font-semibold text-gray-700 hover:bg-gray-50 transition-colors"
                  >
                    Cancelar
                  </button>
                  <button
                    type="submit"
                    className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-lg font-semibold transition-colors"
                  >
                    {editingMaterial ? 'Atualizar' : 'Criar'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}

// frontend/src/pages/Materials.vue
<template>
  <Layout>
    <div class="flex flex-col h-full">
      
      <div class="flex justify-between items-center mb-6 px-4 pt-4">
        <div>
          <h1 class="text-2xl font-bold text-gray-800">Materiais</h1>
          <p class="text-sm text-gray-500">Gerenciamento de Estoque</p>
        </div>
        <button 
          @click="openCreateModal"
          class="bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded flex items-center gap-2 shadow-sm transition-colors"
        >
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M10 3a1 1 0 011 1v5h5a1 1 0 110 2h-5v5a1 1 0 11-2 0v-5H4a1 1 0 110-2h5V4a1 1 0 011-1z" clip-rule="evenodd" />
          </svg>
          <span>Novo Material</span>
        </button>
      </div>

      <div class="bg-white p-4 rounded shadow-sm border border-gray-200 mx-4 mb-4 flex gap-4">
        <div class="w-1/3">
          <label class="block text-xs font-bold text-gray-500 uppercase mb-1">Categoria</label>
          <select v-model="selectedCategory" class="w-full border p-2 rounded outline-none focus:border-blue-500 bg-white">
            <option v-for="cat in categories" :key="cat" :value="cat">{{ cat }}</option>
          </select>
        </div>
        <div class="w-2/3">
          <label class="block text-xs font-bold text-gray-500 uppercase mb-1">Buscar</label>
          <input 
            v-model="search" 
            type="text" 
            placeholder="Pesquise por código ou nome..." 
            class="w-full border p-2 rounded outline-none focus:border-blue-500"
          />
        </div>
      </div>

      <div class="flex-1 overflow-auto px-4 pb-4">
        <div class="bg-white rounded shadow border border-gray-200">
          <table class="w-full text-left border-collapse">
            <thead class="bg-gray-50 sticky top-0 z-10">
              <tr>
                <th class="px-4 py-3 text-xs font-bold text-gray-500 uppercase border-b">Código</th>
                <th class="px-4 py-3 text-xs font-bold text-gray-500 uppercase border-b">Descrição</th>
                <th class="px-4 py-3 text-xs font-bold text-gray-500 uppercase border-b text-center">Categ.</th>
                <th class="px-4 py-3 text-xs font-bold text-gray-500 uppercase border-b text-right">Qtd / Medida</th>
                <th class="px-4 py-3 text-xs font-bold text-gray-500 uppercase border-b text-center">Ações</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="item in paginatedMaterials" :key="item.id" class="hover:bg-gray-50 border-b last:border-0 transition-colors">
                <td class="px-4 py-3 font-mono text-sm font-bold text-blue-600">{{ item.code }}</td>
                <td class="px-4 py-3 text-sm text-gray-700 font-medium">{{ item.name }}</td>
                <td class="px-4 py-3 text-center">
                  <span class="px-2 py-1 text-xs bg-gray-100 rounded-full font-bold text-gray-600 border border-gray-200">{{ item.type }}</span>
                </td>
                <td class="px-4 py-3 text-right font-bold text-gray-800">
                  {{ formatNumber(item.quantity) }} 
                  <span class="text-xs bg-blue-50 text-blue-800 px-1 rounded ml-1 border border-blue-100">{{ item.unit }}</span>
                </td>
                <td class="px-4 py-3 text-center">
                  <div class="flex items-center justify-center gap-3">
                    <button @click="viewDetails(item)" class="text-gray-400 hover:text-blue-600 transition-colors" title="Visualizar Detalhes">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" /><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" /></svg>
                    </button>
                    <button @click="editItem(item)" class="text-gray-400 hover:text-orange-500 transition-colors" title="Editar">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" /></svg>
                    </button>
                    <button @click="confirmDelete(item)" class="text-gray-400 hover:text-red-600 transition-colors" title="Excluir">
                      <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                  </button>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div v-if="viewingItem" class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 p-4">
        <div class="bg-white rounded-lg shadow-xl w-full max-w-md overflow-hidden">
          <div class="bg-gray-50 px-6 py-4 border-b flex justify-between items-center">
            <h3 class="font-bold text-gray-800">Detalhes do Material</h3>
            <button @click="viewingItem = null" class="text-gray-400 hover:text-gray-600 font-bold text-xl">&times;</button>
          </div>
          <div class="p-6 space-y-4">
            <div class="flex justify-center mb-2">
              <span class="bg-blue-100 text-blue-800 px-3 py-1 rounded text-lg font-mono font-bold border border-blue-200">{{ viewingItem.code }}</span>
            </div>
            <div>
              <label class="block text-xs font-bold text-gray-500 uppercase">Nome</label>
              <div class="text-gray-900 font-medium">{{ viewingItem.name }}</div>
            </div>
            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="block text-xs font-bold text-gray-500 uppercase">Unidade</label>
                <div class="text-gray-900 font-bold">{{ viewingItem.unit }}</div>
              </div>
              <div>
                <label class="block text-xs font-bold text-gray-500 uppercase">Estoque</label>
                <div class="text-gray-900 font-bold">{{ formatNumber(viewingItem.quantity) }}</div>
              </div>
            </div>
            <div>
              <label class="block text-xs font-bold text-gray-500 uppercase">Localização</label>
              <div class="text-gray-900">{{ viewingItem.location || 'Não informada' }}</div>
            </div>
             <div>
              <label class="block text-xs font-bold text-gray-500 uppercase">Observação</label>
              <div class="text-gray-900 bg-gray-50 p-2 rounded border border-gray-100 text-sm">{{ viewingItem.observation || 'Nenhuma observação' }}</div>
            </div>
          </div>
          <div class="px-6 py-4 bg-gray-50 text-right">
            <button @click="viewingItem = null" class="px-4 py-2 bg-gray-800 text-white rounded hover:bg-gray-900 text-sm">Fechar</button>
          </div>
        </div>
      </div>

      <div v-if="showCreateModal" class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50 p-4">
        <div class="bg-white rounded-lg shadow-xl w-full max-w-md p-6">
          <h2 class="text-lg font-bold mb-4 text-gray-800">{{ editingItem ? 'Editar' : 'Novo Material' }}</h2>
          <form @submit.prevent="saveItem" class="space-y-4">
            
            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1">Código</label>
              <input v-model="form.code" required class="w-full border p-2 rounded outline-none font-mono" placeholder="Ex: 1040" />
            </div>

            <div>
              <label class="block text-sm font-bold text-gray-700 mb-1">Descrição</label>
              <input v-model="form.name" required class="w-full border p-2 rounded outline-none" />
            </div>

            <div class="grid grid-cols-2 gap-4">
              <div>
                <label class="block text-sm font-bold text-gray-700 mb-1">Categoria</label>
                <select v-model="form.type" class="w-full border p-2 rounded bg-white outline-none">
                  <option v-for="cat in categories.filter(c => c !== 'Todos')" :key="cat" :value="cat">{{ cat }}</option>
                </select>
              </div>
              
              <div>
                <label class="block text-sm font-bold text-gray-700 mb-1">Unidade</label>
                <select v-model="form.unit" class="w-full border p-2 rounded bg-white outline-none font-medium">
                  <option value="und">Unidade (und)</option>
                  <option value="kg">Quilograma (kg)</option>
                  <option value="m">Metro (m)</option>
                  <option value="m²">Metro Quadrado (m²)</option>
                  <option value="g">Grama (g)</option>
                  <option value="par">Par</option>
                  <option value="cx">Caixa</option>
                  <option value="rl">Rolo</option>
                </select>
              </div>
            </div>

            <div class="grid grid-cols-2 gap-4">
               <div>
                <label class="block text-sm font-bold text-gray-700 mb-1">Estoque Inicial</label>
                <input type="number" step="0.01" v-model.number="form.quantity" class="w-full border p-2 rounded outline-none" />
              </div>
              <div>
                 <label class="block text-sm font-bold text-gray-700 mb-1">Localização</label>
                 <input v-model="form.location" class="w-full border p-2 rounded outline-none" placeholder="Opcional" />
              </div>
            </div>
            
            <div>
                <label class="block text-sm font-bold text-gray-700 mb-1">Observação</label>
                <textarea v-model="form.observation" class="w-full border p-2 rounded outline-none h-20 resize-none" placeholder="Detalhes adicionais..."></textarea>
              </div>

            <div class="flex justify-end gap-2 mt-4 pt-4 border-t">
              <button type="button" @click="showCreateModal = false" class="px-4 py-2 bg-gray-100 text-gray-700 rounded hover:bg-gray-200">Cancelar</button>
              <button type="submit" class="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">Salvar</button>
            </div>
          </form>
        </div>
      </div>

    </div>
  </Layout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import Layout from '../components/Layout.vue'

const API_URL = 'http://localhost:3000'
const materials = ref([])
const search = ref('')
const selectedCategory = ref('Todos')
const showCreateModal = ref(false)
const editingItem = ref(null)
const viewingItem = ref(null)

const form = ref({ code: '', name: '', type: 'OUTROS', unit: 'und', quantity: 0, location: '', observation: '' })

const categories = ['Todos', 'TECIDO', 'LINHA', 'ELASTICO', 'AVIAMENTO', 'COURO', 'SINTETICO', 'SOLADO', 'FILME', 'EVA', 'ESPUMA', 'FORRO', 'MANTA', 'MICROFIBRA', 'FERRAMENTAIS', 'OUTROS']

async function fetchMaterials() {
  try {
    const res = await fetch(`${API_URL}/materials`)
    materials.value = await res.json()
  } catch (e) { console.error(e) }
}

const paginatedMaterials = computed(() => {
  return materials.value.filter(m => {
    const term = search.value.toLowerCase()
    return (selectedCategory.value === 'Todos' || m.type === selectedCategory.value) &&
           (m.name.toLowerCase().includes(term) || String(m.code).toLowerCase().includes(term))
  }).sort((a,b) => b.id - a.id).slice(0, 50)
})

function formatNumber(num) { return Number(num).toLocaleString('pt-BR', { minimumFractionDigits: 0, maximumFractionDigits: 3 }) }

function openCreateModal() {
  editingItem.value = null
  form.value = { code: '', name: '', type: 'OUTROS', unit: 'und', quantity: 0, location: '', observation: '' }
  showCreateModal.value = true
}

function editItem(item) {
  editingItem.value = item
  form.value = { ...item }
  showCreateModal.value = true
}

function viewDetails(item) { viewingItem.value = item }

async function saveItem() {
  try {
    const userJson = localStorage.getItem('user');
    const user = userJson ? JSON.parse(userJson) : null;
    const userId = user ? user.id : 1; 

    const method = editingItem.value ? 'PUT' : 'POST'
    const url = editingItem.value ? `${API_URL}/materials/${editingItem.value.id}` : `${API_URL}/materials`
    
    const payload = { ...form.value, userId } 
    if (!editingItem.value) delete payload.id 

    const res = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) })
    
    if (res.ok) {
      alert('Salvo com sucesso!')
      showCreateModal.value = false
      await fetchMaterials()
    } else {
      alert('Erro: Verifique se o código já existe.')
    }
  } catch (e) { alert('Erro de conexão.') }
}

async function confirmDelete(item) {
  if (confirm('Tem certeza? A exclusão será registrada.')) {
    await fetch(`${API_URL}/materials/${item.id}`, { method: 'DELETE' })
    fetchMaterials()
  }
}

onMounted(fetchMaterials)
</script>
